version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talent-match-api
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      - URL_DB=postgres  # Use service name instead of localhost
    networks:
      - talent-network

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: talent-match-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - talent-network
  
  postgres:
    image: ankane/pgvector:latest
    container_name: postgres-database
    environment:
      POSTGRES_DB: talent_match
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d talent_match"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - talent-network

volumes:
  postgres-data:
  ollama_data:

networks:
  talent-network:
    driver: bridge