version: '3.8'
services:
  postgres-vector:
    image: ankane/pgvector:latest
    container_name: postgres-database
    environment:
      POSTGRES_DB: talent_match
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d talent_match"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: